{% set name = "Flask-Cors" %}
{% set version = "3.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b60839393f3b84a0f3746f6cdca56c1ad7426aa738b70d6c61375857823181de

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - flask >=0.9
    - six

test:
  imports:
    - flask_cors
    - flask_cors.core
    - flask_cors.decorator
    - flask_cors.extension
    - flask_cors.version
  commands:
    - pip check
  requires: 
    - pip

about:
  home: https://github.com/corydolphin/flask-cors
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'A Flask extension adding a decorator for CORS support'
  doc_url: http://flask-cors.corydolphin.com/en/latest/
  dev_url: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
